server:
  port: 8083
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: proyect_final
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: ""
    password: ""



